### ISSUE TITLE
How to enable yaw control

### ISSUE THREAD

**Issue by surfii3z** [JD-ETH/AirSimNeurIPS#2]
Hi

I am really impressed by your work.

I would like to try your algorithm out in tier2 and tier3 as well (combining with perception, of course).

My idea is to detect gate in the FPV then infers its position and relative orientation and use this as one of the point to go.

However, to do so, I would need the drone to control yaw angle as well.

Could you please let me know of where to start to look at?

Best Regards,

Surfii3z

**Comment by JD-ETH** [comment]
Hi @surfii3z. glad that you like it! 

I wish you good luck with the tier2 and tier3. Frankly I had planned to do that as well, however it turned out much more difficult that I thought: The rendering was just too pretty to reliably detect the gates :rofl: 

What I had in mind: 
1. At the end of planning stage, compute an additional yaw correction that is necessary and assume a smooth transition so that you can directly add it to the planned trajectory. So the planning algorithm originally doesn't care about yaw as it is independent. However, you know roughly how the gates should look so you could try to align yourself in that orientation already. Obviously the realistic cases are much more complicated than that (gate can oriented such that it looks up or downwards), so you need to be careful with how you decompose rotation. 


2. Be also very careful in the control stage. If you know some drone dynamics, you will realize that a drone has much control in yaw axis than in the rest of them. Ideally you want to incorporate that into your control problem and avoid unrealistic control problem as we try to operate on the limit. 

Good luck and have fun!

**Comment by surfii3z** [comment]
Thanks for the ideas!
